apiVersion: v1
data:
  images: |
    [
      {
        "image": "{{.Values.global.registry.address}}/{{.Values.global.images.productDocs.repository}}:{{.Values.global.images.productDocs.tag}}",
        "destDir": "/docs",
        "sourceDir": "/dist/docs"
      }
    ]
kind: ConfigMap
metadata:
  finalizers:
  - alauda.io/image-loader
  labels:
    image-load-config: "true"
  name: "product-docs{{ .Values.resourceSuffix }}"
  namespace: {{ .Values.global.namespace }}