apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if .Values.global.ingress.annotations}}
    {{- range $name, $val:= .Values.global.ingress.annotations }}
    {{ $name }}: {{ $val | quote }}
    {{- end }}
{{- end }}
  labels:
    service_name: "alauda-product-docs{{ .Values.resourceSuffix }}"
  name: "alauda-product-docs{{ .Values.resourceSuffix }}"
  namespace: {{ .Values.global.namespace }}
spec:
{{- if .Values.productDocs.ingress.ingressClassName }}
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
{{- end }}
{{- if .Values.productDocs.ingress.host }}
  tls:
    - hosts:
        - {{ .Values.productDocs.ingress.host }}
      {{- if .Values.productDocs.ingress.tlsSecret }}
      secretName: {{ .Values.productDocs.ingress.tlsSecret }}
      {{- end }}
{{- end }}
  rules:
    - http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 8080
            path: /docs/(.*)
            pathType: ImplementationSpecific
{{- if .Values.productDocs.ingress.host }}
      host: {{ .Values.productDocs.ingress.host }}
{{- end }}